LoadModule _1cws_module /opt/1C/v8.3/x86_64/wsap24.so

Alias "/rat" "/usr/local/apache2/htdocs/rat/"
<Directory "/usr/local/apache2/htdocs/rat">
    AllowOverride All
    Options None
    Require all granted
    SetHandler 1c-application
    ManagedApplicationDescriptor "/usr/local/apache2/htdocs/rat/default.vrd"
</Directory>